//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class profile
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string identityNumber { get; set; }
        public System.DateTime birthday { get; set; }
        public string address { get; set; }
        public string nation { get; set; }
        public string religion { get; set; }
    }
}
